; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Penilaian Tanah V6.2.1"
#define MyAppVersion "V6.2.1"
#define MyAppVersionName "Balikpapan"
#define MyAppPublisher "Direktorat Penilaian Tanah dan Ekonomi Pertanahan Kementerian ATR/BPN"
#define MyAppURL "https://sipenta.atrbpn.go.id/"
#define MyAppExeName "SIPENTA.aprx"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} 
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\PenilaianTanah
DisableDirPage=yes
DisableProgramGroupPage=yes
Uninstallable=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=Penilaian Tanah V6.2.1
SetupIconFile=icons\penilaian_tanah.ico
; Gunakan kode dibawah untuk memunculkan icon aplikasi di Control Panel
UninstallDisplayIcon={uninstallexe}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"    

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "*"; DestDir: "C:\PenilaianTanah\"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: ".git\*,.github\*,.vscode\*,Output\*,*.iss,.gitignore,.gitattributes,README.txt"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "C:\PenilaianTanah\SIPENTA\{#MyAppExeName}"; IconFilename: "C:\PenilaianTanah\icons\penilaian_tanah.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "C:\PenilaianTanah\SIPENTA\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "C:\PenilaianTanah\icons\penilaian_tanah.ico"

[Run]
Filename: "C:\PenilaianTanah\ui\start.bat"; StatusMsg: "Install Start.bat..."; Flags: runhidden

[Code]

function GetUninstallString(): string;
var
  UninstallString: string;
begin
  if not RegQueryStringValue(
    HKLM,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}_is1',
    'UninstallString',
    UninstallString
  ) then
  begin
    RegQueryStringValue(
      HKCU,
      'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}_is1',
      'UninstallString',
      UninstallString
    );
  end;

  Result := UninstallString;
end;

function InitializeSetup(): Boolean;
var
  UninstallString: string;
  ResultCode: Integer;
begin
  UninstallString := GetUninstallString();

  if UninstallString <> '' then
  begin
    Exec(RemoveQuotes(UninstallString),
         '/VERYSILENT /NORESTART',
         '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;

  Result := True;
end;

[InstallDelete]
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.6.2d - Humbang Hasundutan.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.6.1 - Humbang Hasundutan.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.6.2 - Humbassng Hasundutan.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.6 - Humbang Hasundutan.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.7 - Intan Jaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.7.1 - Intan Jaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.1 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8 d1 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.2 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.3 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.4 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.5 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V5.8.6 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6 - Jayawijaya.lnk"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6 - Aceh Barat Daya"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6.0.1 - Aceh Barat Daya"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6.1 - Balikpapan"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6.1.1 - Balikpapan"
Type: files; Name: "{autodesktop}\Penilaian Tanah V6.2"

[UninstallDelete]    
Type: files; Name: "{%USERPROFILE}\AppData\Local\ESRI\Arcgis.Desktop.Config.daml"
