; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Penilaian Tanah V6.3"
#define MyAppVersion "V6.3"
#define MyAppPublisher "Direktorat Penilaian Tanah dan Ekonomi Pertanahan Kementerian ATR/BPN"
#define MyAppURL "https://sipenta.atrbpn.go.id/"
#define MyAppExeName "SIPENTA.aprx"

[Setup]
AppId={{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} 
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName=C:\PenilaianTanah
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputDir=Output
OutputBaseFilename=Penilaian_Tanah
SetupIconFile=icons\penilaian_tanah.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"    

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: ".git\*,.github\*,.vscode\*,Output\*,*.iss,.gitignore,.gitattributes,README.txt"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\SIPENTA\{#MyAppExeName}"; IconFilename: "{app}\icons\penilaian_tanah.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\SIPENTA\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\icons\penilaian_tanah.ico"

[Run]
Filename: "{app}\ui\start.bat"; StatusMsg: "Install Start.bat..."; Flags: runhidden

[Code]
function GetUninstallString(): string;
var
  UninstallString: string;
begin
  if not RegQueryStringValue(
    HKLM,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}_is1',
    'UninstallString',
    UninstallString
  ) then
  begin
    RegQueryStringValue(
      HKCU,
      'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{9C9EB90C-9CAE-4B67-86DF-B3B1A9316D21}}_is1',
      'UninstallString',
      UninstallString
    );
  end;

  Result := UninstallString;
end;

function InitializeSetup(): Boolean;
var
  UninstallString: string;
  ResultCode: Integer;
begin
  UninstallString := GetUninstallString();

  if UninstallString <> '' then
  begin
    Exec(RemoveQuotes(UninstallString),
         '/VERYSILENT /NORESTART',
         '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;

  Result := True;
end;

[InstallDelete]
Type: files; Name: "{autodesktop}\Penilaian Tanah*.lnk"

[UninstallDelete]    
Type: files; Name: "{%USERPROFILE}\AppData\Local\ESRI\Arcgis.Desktop.Config.daml"