# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-11-11 08:37:31
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def Setep3(Input_Feature, Explanatory_Variable, Metode, Maximum_Number_of_Explanatory_Variable, Minimum_Number_of_Explanatory_Variable):  # Setep 3
    #set ws dll
    

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = TRUE

    Values = "Ordinary Least Squares (OLS)"

    # Process: If Value Is (If Value Is) 
    True_17, False_18 = #  NOT  IMPLEMENTED(input_value=Metode, value_test="IS_EQUAL_TO_ANY", comparison_type="STRING_CASE_INSENSITIVE", values=[Values], range_values=[], comparison_value="")

    # Process: Ordinary Least Squares (OLS) (Ordinary Least Squares (OLS)) 
    OLS_Result = "C:\\Pentabit2\\sys\\temporary.gdb\\OLS_Result"
    if True_17:
        arcpy.OrdinaryLeastSquares_stats(
            Input_Feature_Class=Input_Feature, 
            Unique_ID_Field="IdBidang", 
            Output_Feature_Class=OLS_Result, 
            Dependent_Variable="nilai", 
            Explanatory_Variables=Explanatory_Variable, 
            Coefficient_Output_Table=OLS_Coeff, 
            Diagnostic_Output_Table=OLS_Diag, 
            Output_Report_File=OLS_Report)

    # Process: Exploratory Regression (Exploratory Regression) 
    if False_18 and Maximum_Number_of_Explanatory_Variable and Minimum_Number_of_Explanatory_Variable:
        arcpy.ExploratoryRegression_stats(
            Input_Features=Input_Feature, 
            Dependent_Variable="nilai", 
            Candidate_Explanatory_Variables=Explanatory_Variable, 
            Weights_Matrix_File="", 
            Output_Report_File=ER_Report, 
            Output_Results_Table=ER_Result, 
            Maximum_Number_of_Explanatory_Variables=5, 
            Minimum_Number_of_Explanatory_Variables=1, 
            Minimum_Acceptable_Adj_R_Squared=0,5, 
            Maximum_Coefficient_p_value_Cutoff=0,05, 
            Maximum_VIF_Value_Cutoff=7,5, 
            Minimum_Acceptable_Jarque_Bera_p_value=0,1, 
            Minimum_Acceptable_Spatial_Autocorrelation_p_value=0,1)

if __name__ == '__main__':
    # Global Environment settings
    #with arcpy.EnvManager(scratchWorkspace=r"C:\Users\DELL\Desktop\ArcPro\ArcPro\Default.gdb", workspace=r"C:\Users\DELL\Desktop\ArcPro\ArcPro\Default.gdb"):
    Setep3(*argv[1:])
