NAMA_PROVINSI = [
  "Aceh",
  "Bali",
  "Banten",
  "Bengkulu",
  "Daerah Istimewa Yogyakarta",
  "DKI Jakarta",
  "Gorontalo",
  "Jambi",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Kalimantan Barat",
  "Kalimantan Selatan",
  "Kalimantan Tengah",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "Lampung",
  "Maluku",
  "Maluku Utara",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Papua",
  "Papua Barat",
  "Papua Barat Daya",
  "Papua Pegunungan",
  "Papua Selatan",
  "Papua Tengah",
  "Riau",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tengah",
  "Sulawesi Tenggara",
  "Sulawesi Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Sumatera Utara"
]

KAB_KOTA = {
    "Aceh": [
        "Aceh Barat",
        "Aceh Barat Daya",
        "Aceh Besar",
        "Aceh Jaya",
        "Aceh Selatan",
        "Aceh Singkil",
        "Aceh Tamiang",
        "Aceh Tengah",
        "Aceh Tenggara",
        "Aceh Timur",
        "Aceh Utara",
        "Bener Meriah",
        "Bireuen",
        "Gayo Lues",
        "Nagan Raya",
        "Pidie",
        "Pidie Jaya",
        "Simeulue",
        "Kota Banda Aceh",
        "Kota Langsa",
        "Kota Lhokseumawe",
        "Kota Sabang",
        "Kota Subulussalam"
    ],
    "Sumatera Utara": [
        "Asahan",
        "Batu Bara",
        "Dairi",
        "Deli Serdang",
        "Humbang Hasundutan",
        "Karo",
        "Labuhanbatu",
        "Labuhanbatu Selatan",
        "Labuhanbatu Utara",
        "Langkat",
        "Mandailing Natal",
        "Nias",
        "Nias Barat",
        "Nias Selatan",
        "Nias Utara",
        "Padang Lawas",
        "Padang Lawas Utara",
        "Pakpak Bharat",
        "Samosir",
        "Serdang Bedagai",
        "Simalungun",
        "Tapanuli Selatan",
        "Tapanuli Tengah",
        "Tapanuli Utara",
        "Toba",
        "Kota Binjai",
        "Kota Gunungsitoli",
        "Kota Medan",
        "Kota Padangsidimpuan",
        "Kota Pematangsiantar",
        "Kota Sibolga",
        "Kota Tanjungbalai",
        "Kota Tebing Tinggi"
    ],
    "Sumatera Barat": [
        "Agam",
        "Dharmasraya",
        "Kepulauan Mentawai",
        "Lima Puluh Kota",
        "Padang Pariaman",
        "Pasaman",
        "Pasaman Barat",
        "Pesisir Selatan",
        "Sijunjung",
        "Solok",
        "Solok Selatan",
        "Tanah Datar",
        "Kota Bukittinggi",
        "Kota Padang",
        "Kota Padang Panjang",
        "Kota Pariaman",
        "Kota Payakumbuh",
        "Kota Sawahlunto",
        "Kota Solok"
    ],
    "Riau": [
        "Bengkalis",
        "Indragiri Hilir",
        "Indragiri Hulu",
        "Kampar",
        "Kepulauan Meranti",
        "Kuantan Singingi",
        "Pelalawan",
        "Rokan Hilir",
        "Rokan Hulu",
        "Siak",
        "Kota Dumai",
        "Kota Pekanbaru"
    ],
    "Jambi": [
        "Batanghari",
        "Bungo",
        "Kerinci",
        "Merangin",
        "Muaro Jambi",
        "Sarolangun",
        "Tanjung Jabung Barat",
        "Tanjung Jabung Timur",
        "Tebo",
        "Kota Jambi",
        "Kota Sungai Penuh"
    ],
    "Sumatera Selatan": [
        "Banyuasin",
        "Empat Lawang",
        "Lahat",
        "Muara Enim",
        "Musi Banyuasin",
        "Musi Rawas",
        "Musi Rawas Utara",
        "Ogan Ilir",
        "Ogan Komering Ilir",
        "Ogan Komering Ulu",
        "Ogan Komering Ulu Selatan",
        "Ogan Komering Ulu Timur",
        "Penukal Abab Lematang Ilir",
        "Kota Lubuk Linggau",
        "Kota Pagar Alam",
        "Kota Palembang",
        "Kota Prabumulih"
    ],

    "Bengkulu": [
        "Bengkulu Selatan",
        "Bengkulu Tengah",
        "Bengkulu Utara",
        "Kaur",
        "Kepahiang",
        "Lebong",
        "Mukomuko",
        "Rejang Lebong",
        "Seluma",
        "Kota Bengkulu"
    ],

    "Lampung": [
        "Lampung Barat",
        "Lampung Selatan",
        "Lampung Tengah",
        "Lampung Timur",
        "Lampung Utara",
        "Mesuji",
        "Pesawaran",
        "Pesisir Barat",
        "Pringsewu",
        "Tanggamus",
        "Tulang Bawang",
        "Tulang Bawang Barat",
        "Way Kanan",
        "Kota Bandar Lampung",
        "Kota Metro"
    ],
    "Kepulauan Bangka Belitung": [
        "Bangka",
        "Bangka Barat",
        "Bangka Selatan",
        "Bangka Tengah",
        "Belitung",
        "Belitung Timur",
        "Kota Pangkal Pinang"
    ],
    "Kepulauan Riau": [
        "Bintan",
        "Karimun",
        "Kepulauan Anambas",
        "Lingga",
        "Natuna",
        "Kota Batam",
        "Kota Tanjung Pinang"
    ],
    "DKI Jakarta": [
        "Kepulauan Seribu",
        "Kota Jakarta Barat",
        "Kota Jakarta Pusat",
        "Kota Jakarta Selatan",
        "Kota Jakarta Timur",
        "Kota Jakarta Utara"
    ],
    "Jawa Barat": [
        "Bandung",
        "Bandung Barat",
        "Bekasi",
        "Bogor",
        "Ciamis",
        "Cianjur",
        "Cirebon",
        "Garut",
        "Indramayu",
        "Karawang",
        "Kuningan",
        "Majalengka",
        "Pangandaran",
        "Purwakarta",
        "Sukabumi",
        "Sumedang",
        "Subang",
        "Tasikmalaya",
        "Kota Banjar",
        "Kota Bandung",
        "Kota Bekasi",
        "Kota Bogor",
        "Kota Cimahi",
        "Kota Cirebon",
        "Kota Depok",
        "Kota Sukabumi",
        "Kota Tasikmalaya"
    ],
    "Jawa Tengah": [
        "Banyumas",
        "Batang",
        "Blora",
        "Boyolali",
        "Brebes",
        "Cilacap",
        "Demak",
        "Grobogan",
        "Jepara",
        "Karanganyar",
        "Kebumen",
        "Kendal",
        "Klaten",
        "Kudus",
        "Magelang",
        "Pati",
        "Pekalongan",
        "Pemalang",
        "Purbalingga",
        "Purworejo",
        "Rembang",
        "Semarang",
        "Sragen",
        "Sukoharjo",
        "Tegal",
        "Temanggung",
        "Wonogiri",
        "Wonosobo",
        "Kota Magelang",
        "Kota Pekalongan",
        "Kota Salatiga",
        "Kota Semarang",
        "Kota Surakarta",
        "Kota Tegal"
    ],

    "Daerah Istimewa Yogyakarta": [
        "Bantul",
        "Gunungkidul",
        "Kulon Progo",
        "Sleman",
        "Kota Yogyakarta"
    ],
    "Jawa Timur": [
        "Bangkalan",
        "Banyuwangi",
        "Bojonegoro",
        "Bondowoso",
        "Blitar",
        "Bojonegoro",
        "Gresik",
        "Jember",
        "Jombang",
        "Kediri",
        "Lamongan",
        "Lumajang",
        "Madiun",
        "Magetan",
        "Malang",
        "Mojokerto",
        "Nganjuk",
        "Ngawi",
        "Pacitan",
        "Pamekasan",
        "Pasuruan",
        "Ponorogo",
        "Probolinggo",
        "Sampang",
        "Sidoarjo",
        "Situbondo",
        "Sumenep",
        "Trenggalek",
        "Tuban",
        "Tulungagung",
        "Kota Batu",
        "Kota Blitar",
        "Kota Kediri",
        "Kota Madiun",
        "Kota Malang",
        "Kota Mojokerto",
        "Kota Probolinggo",
        "Kota Pasuruan",
        "Kota Surabaya"
    ],
    "Banten": [
        "Pandeglang",
        "Serang",
        "Tangerang",
        "Kota Cilegon",
        "Kota Serang",
        "Kota Tangerang",
        "Kota Tangerang Selatan"
    ],
    "Bali": [
        "Badung",
        "Bangli",
        "Buleleng",
        "Gianyar",
        "Jembrana",
        "Karangasem",
        "Klungkung",
        "Tabanan",
        "Kota Denpasar"
    ],
    "Nusa Tenggara Barat": [
        "Bima",
        "Dompu",
        "Lombok Barat",
        "Lombok Tengah",
        "Lombok Timur",
        "Lombok Utara",
        "Sumbawa",
        "Sumbawa Barat",
        "Kota Bima",
        "Kota Mataram"
    ],
    "Nusa Tenggara Timur": [
        "Alor",
        "Belu",
        "Ende",
        "Flores Timur",
        "Kupang",
        "Malaka",
        "Manggarai",
        "Manggarai Barat",
        "Manggarai Timur",
        "Nagekeo",
        "Ngada",
        "Rote Ndao",
        "Sabu Raijua",
        "Sikka",
        "Sumba Barat",
        "Sumba Barat Daya",
        "Sumba Tengah",
        "Sumba Timur",
        "Timor Tengah Selatan",
        "Timor Tengah Utara",
        "Kota Kupang"
    ],
    "Kalimantan Barat": [
        "Bengkayang",
        "Kapuas Hulu",
        "Kayong Utara",
        "Kubu Raya",
        "Landak",
        "Mempawah",
        "Melawi",
        "Sambas",
        "Sanggau",
        "Sekadau",
        "Sintang",
        "Ketapang",
        "Kota Pontianak",
        "Kota Singkawang"
    ],
    "Kalimantan Tengah": [
        "Barito Kuala",
        "Barito Selatan",
        "Barito Timur",
        "Barito Utara",
        "Gunung Mas",
        "Kapuas",
        "Katingan",
        "Kotawaringin Barat",
        "Kotawaringin Timur",
        "Lamandau",
        "Murung Raya",
        "Pulang Pisau",
        "Seruyan",
        "Sukamara",
        "Kota Palangkaraya"
    ],
    "Kalimantan Selatan": [
        "Balangan",
        "Banjar",
        "Barito Kuala",
        "Hulu Sungai Selatan",
        "Hulu Sungai Tengah",
        "Hulu Sungai Utara",
        "Kotabaru",
        "Tabalong",
        "Tanah Bumbu",
        "Tanah Laut",
        "Tapin",
        "Kota Banjarmasin",
        "Kota Banjarbaru"
    ],
    "Kalimantan Timur": [
        "Berau",
        "Kutai Barat",
        "Kutai Kartanegara",
        "Kutai Timur",
        "Mahakam Ulu",
        "Paser",
        "Penajam Paser Utara",
        "Kota Balikpapan",
        "Kota Bontang",
        "Kota Samarinda"
    ],
    "Kalimantan Utara": [
        "Bulungan",
        "Malinau",
        "Nunukan",
        "Tana Tidung",
        "Kota Tarakan"
    ],
    "Sulawesi Utara": [
        "Bolaang Mongondow",
        "Bolaang Mongondow Selatan",
        "Bolaang Mongondow Timur",
        "Bolaang Mongondow Utara",
        "Kepulauan Sangihe",
        "Kepulauan Siau Tagulandang Biaro",
        "Kepulauan Talaud",
        "Minahasa",
        "Minahasa Selatan",
        "Minahasa Tenggara",
        "Minahasa Utara",
        "Kota Bitung",
        "Kota Kotamobagu",
        "Kota Manado",
        "Kota Tomohon"
    ],
    "Sulawesi Tengah": [
        "Banggai",
        "Banggai Kepulauan",
        "Banggai Laut",
        "Buol",
        "Donggala",
        "Morowali",
        "Morowali Utara",
        "Parigi Moutong",
        "Poso",
        "Sigi",
        "Toli-Toli",
        "Tojo Una Una",
        "Kota Palu"
    ],
    "Sulawesi Selatan": [
        "Bantaeng",
        "Barru",
        "Bone",
        "Bulukumba",
        "Enrekang",
        "Gowa",
        "Jeneponto",
        "Kepulauan Selayar",
        "Luwu",
        "Luwu Timur",
        "Luwu Utara",
        "Maros",
        "Pangkajene dan Kepulauan",
        "Pinrang",
        "Sidenreng Rappang",
        "Sinjai",
        "Soppeng",
        "Takalar",
        "Tana Toraja",
        "Toraja Utara",
        "Wajo",
        "Kota Makassar",
        "Kota Palopo",
        "Kota Parepare"
    ],
    "Sulawesi Tenggara": [
        "Bombana",
        "Buton",
        "Buton Selatan",
        "Buton Tengah",
        "Buton Utara",
        "Kolaka",
        "Kolaka Timur",
        "Kolaka Utara",
        "Konawe",
        "Konawe Kepulauan",
        "Konawe Selatan",
        "Konawe Utara",
        "Muna",
        "Muna Barat",
        "Wakatobi",
        "Kota Bau Bau",
        "Kota Kendari"
    ],
    "Sulawesi Tenggara": [
        "Bombana",
        "Buton",
        "Buton Selatan",
        "Buton Tengah",
        "Buton Utara",
        "Kolaka",
        "Kolaka Timur",
        "Kolaka Utara",
        "Konawe",
        "Konawe Kepulauan",
        "Konawe Selatan",
        "Konawe Utara",
        "Muna",
        "Muna Barat",
        "Wakatobi",
        "Kota Bau Bau",
        "Kota Kendari"
    ],
    "Gorontalo": [
        "Boalemo",
        "Bone Bolango",
        "Gorontalo",
        "Gorontalo Utara",
        "Pahuwato",
        "Kota Gorontalo"
    ],
    "Sulawesi Barat": [
        "Majene",
        "Mamuju",
        "Mamuju Tengah",
        "Mamasa",
        "Pasangkayu",
        "Polewali Mandar"
    ],
    "Maluku": [
        "Buru",
        "Buru Selatan",
        "Kepulauan Aru",
        "Kepulauan Tanimbar",
        "Maluku Barat Daya",
        "Maluku Tengah",
        "Maluku Tenggara",
        "Seram Bagian Barat",
        "Seram Bagian Timur",
        "Kota Ambon",
        "Kota Tual"
    ],
    "Maluku Utara": [
        "Halmahera Barat",
        "Halmahera Selatan",
        "Halmahera Tengah",
        "Halmahera Timur",
        "Halmahera Utara",
        "Kepulauan Sula",
        "Pulau Morotai",
        "Pulau Taliabu",
        "Kota Ternate",
        "Kota Tidore Kepulauan"
    ],
    "Papua": [
        "Biak Numfor",
        "Jayapura",
        "Keerom",
        "Kepulauan Yapen",
        "Mamberamo Raya",
        "Sarmi",
        "Supiori",
        "Waropen",
        "Kota Jayapura"
    ],
    "Papua Barat": [
        "Fak Fak",
        "Kaimana",
        "Manokwari",
        "Manokwari Selatan",
        "Pegunungan Arfak",
        "Teluk Bintuni",
        "Teluk Wondama"
    ],
    "Papua Selatan": [
        "Asmat",
        "Boven Digoel",
        "Mappi",
        "Merauke"
    ],
    "Papua Tengah": [
        "Deiyai",
        "Dogiyai",
        "Intan Jaya",
        "Mimika",
        "Nabire",
        "Paniai",
        "Puncak",
        "Puncak Jaya"
    ],
    "Papua Pegunungan": [
        "Jayawijaya",
        "Lanny Jaya",
        "Mamberamo Tengah",
        "Nduga",
        "Pegunungan Bintang",
        "Tolikara",
        "Yahukimo",
        "Yalimo"
    ],
    "Papua Barat Daya": [
        "Maybrat",
        "Raja Ampat",
        "Sorong",
        "Sorong Selatan",
        "Tambrauw",
        "Kota Sorong"
    ],
}

VERSION_NUMBER = '5.8.5'
VERSION_NAME = 'Jayawijaya'
VERSION_ID = 'solo-bandung-padang-69e0901d-ezx'
CURRENT_VERSION = f'{VERSION_NUMBER} - {VERSION_NAME}'
SIPENTA_SERVER_INSTALLER_URL = 'https://belajar.atrbpn.go.id/sipenta/tatausaha/apis/installer'
UPDATE_URL = "https://raw.githubusercontent.com/Akring-creator/update-version-repo/main/realease-notes.json"
USER_DATA_KEY = "sipenta_user_data"
NIK_KEY = "nomor_induk_kependudukan"
NOMOR_KONTRAK_KEY = "nomor_kontrak"
PREFERRED_SERVER_KEY = "preferred_server"